//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valiasr.UI.WPF.ServiceReferencePerson {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://schemas.datacontract.org/2004/07/Valiasr.Service")]
    [System.SerializableAttribute()]
    public partial class PersonDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CretyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CretySerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadNationalIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTelnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndivOrOrganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short JobKindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeTelNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaderehField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShobehCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CretyId {
            get {
                return this.CretyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CretyIdField, value) != true)) {
                    this.CretyIdField = value;
                    this.RaisePropertyChanged("CretyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CretySerial {
            get {
                return this.CretySerialField;
            }
            set {
                if ((object.ReferenceEquals(this.CretySerialField, value) != true)) {
                    this.CretySerialField = value;
                    this.RaisePropertyChanged("CretySerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName {
            get {
                return this.FatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherNameField, value) != true)) {
                    this.FatherNameField = value;
                    this.RaisePropertyChanged("FatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadNationalIdentity {
            get {
                return this.HeadNationalIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadNationalIdentityField, value) != true)) {
                    this.HeadNationalIdentityField = value;
                    this.RaisePropertyChanged("HeadNationalIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTelno {
            get {
                return this.HomeTelnoField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTelnoField, value) != true)) {
                    this.HomeTelnoField = value;
                    this.RaisePropertyChanged("HomeTelno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndivOrOrgan {
            get {
                return this.IndivOrOrganField;
            }
            set {
                if ((object.ReferenceEquals(this.IndivOrOrganField, value) != true)) {
                    this.IndivOrOrganField = value;
                    this.RaisePropertyChanged("IndivOrOrgan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short JobKind {
            get {
                return this.JobKindField;
            }
            set {
                if ((this.JobKindField.Equals(value) != true)) {
                    this.JobKindField = value;
                    this.RaisePropertyChanged("JobKind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName {
            get {
                return this.JobNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNameField, value) != true)) {
                    this.JobNameField = value;
                    this.RaisePropertyChanged("JobName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalIdentity {
            get {
                return this.NationalIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdentityField, value) != true)) {
                    this.NationalIdentityField = value;
                    this.RaisePropertyChanged("NationalIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeTelNo {
            get {
                return this.OfficeTelNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeTelNoField, value) != true)) {
                    this.OfficeTelNoField = value;
                    this.RaisePropertyChanged("OfficeTelNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalIdentity {
            get {
                return this.PostalIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalIdentityField, value) != true)) {
                    this.PostalIdentityField = value;
                    this.RaisePropertyChanged("PostalIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sadereh {
            get {
                return this.SaderehField;
            }
            set {
                if ((object.ReferenceEquals(this.SaderehField, value) != true)) {
                    this.SaderehField = value;
                    this.RaisePropertyChanged("Sadereh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShobehCode {
            get {
                return this.ShobehCodeField;
            }
            set {
                if ((this.ShobehCodeField.Equals(value) != true)) {
                    this.ShobehCodeField = value;
                    this.RaisePropertyChanged("ShobehCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkAddress {
            get {
                return this.WorkAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAddressField, value) != true)) {
                    this.WorkAddressField = value;
                    this.RaisePropertyChanged("WorkAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://schemas.datacontract.org/2004/07/Valiasr.Service")]
    [System.SerializableAttribute()]
    public partial class CustomerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HagheBardashtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PortionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HagheBardasht {
            get {
                return this.HagheBardashtField;
            }
            set {
                if ((this.HagheBardashtField.Equals(value) != true)) {
                    this.HagheBardashtField = value;
                    this.RaisePropertyChanged("HagheBardasht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Portion {
            get {
                return this.PortionField;
            }
            set {
                if ((this.PortionField.Equals(value) != true)) {
                    this.PortionField = value;
                    this.RaisePropertyChanged("Portion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LawyerDto", Namespace="http://schemas.datacontract.org/2004/07/Valiasr.Service")]
    [System.SerializableAttribute()]
    public partial class LawyerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralAccountDto", Namespace="http://schemas.datacontract.org/2004/07/Valiasr.Service")]
    [System.SerializableAttribute()]
    public partial class GeneralAccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndexAccountDto", Namespace="http://schemas.datacontract.org/2004/07/Valiasr.Service")]
    [System.SerializableAttribute()]
    public partial class IndexAccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GeneralAccountCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GeneralAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HaveAccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GeneralAccountCode {
            get {
                return this.GeneralAccountCodeField;
            }
            set {
                if ((this.GeneralAccountCodeField.Equals(value) != true)) {
                    this.GeneralAccountCodeField = value;
                    this.RaisePropertyChanged("GeneralAccountCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GeneralAccountId {
            get {
                return this.GeneralAccountIdField;
            }
            set {
                if ((this.GeneralAccountIdField.Equals(value) != true)) {
                    this.GeneralAccountIdField = value;
                    this.RaisePropertyChanged("GeneralAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HaveAccounts {
            get {
                return this.HaveAccountsField;
            }
            set {
                if ((this.HaveAccountsField.Equals(value) != true)) {
                    this.HaveAccountsField = value;
                    this.RaisePropertyChanged("HaveAccounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowId {
            get {
                return this.RowIdField;
            }
            set {
                if ((this.RowIdField.Equals(value) != true)) {
                    this.RowIdField = value;
                    this.RaisePropertyChanged("RowId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDto", Namespace="http://schemas.datacontract.org/2004/07/Valiasr.Service")]
    [System.SerializableAttribute()]
    public partial class AccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexAccountCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IndexAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndexAccountCode {
            get {
                return this.IndexAccountCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexAccountCodeField, value) != true)) {
                    this.IndexAccountCodeField = value;
                    this.RaisePropertyChanged("IndexAccountCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IndexAccountId {
            get {
                return this.IndexAccountIdField;
            }
            set {
                if ((this.IndexAccountIdField.Equals(value) != true)) {
                    this.IndexAccountIdField = value;
                    this.RaisePropertyChanged("IndexAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowId {
            get {
                return this.RowIdField;
            }
            set {
                if ((this.RowIdField.Equals(value) != true)) {
                    this.RowIdField = value;
                    this.RaisePropertyChanged("RowId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePerson.IPersonAccountService")]
    public interface IPersonAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetPersonByNationalIdentity", ReplyAction="http://tempuri.org/IPersonAccountService/GetPersonByNationalIdentityResponse")]
        Valiasr.UI.WPF.ServiceReferencePerson.PersonDto GetPersonByNationalIdentity(string nationalIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetPersonByNationalIdentity", ReplyAction="http://tempuri.org/IPersonAccountService/GetPersonByNationalIdentityResponse")]
        System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.PersonDto> GetPersonByNationalIdentityAsync(string nationalIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetPersonById", ReplyAction="http://tempuri.org/IPersonAccountService/GetPersonByIdResponse")]
        Valiasr.UI.WPF.ServiceReferencePerson.PersonDto GetPersonById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetPersonById", ReplyAction="http://tempuri.org/IPersonAccountService/GetPersonByIdResponse")]
        System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.PersonDto> GetPersonByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddPerson", ReplyAction="http://tempuri.org/IPersonAccountService/AddPersonResponse")]
        string AddPerson(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddPerson", ReplyAction="http://tempuri.org/IPersonAccountService/AddPersonResponse")]
        System.Threading.Tasks.Task<string> AddPersonAsync(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/UpdatePerson", ReplyAction="http://tempuri.org/IPersonAccountService/UpdatePersonResponse")]
        string UpdatePerson(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/UpdatePerson", ReplyAction="http://tempuri.org/IPersonAccountService/UpdatePersonResponse")]
        System.Threading.Tasks.Task<string> UpdatePersonAsync(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/RemovePerson", ReplyAction="http://tempuri.org/IPersonAccountService/RemovePersonResponse")]
        string RemovePerson(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/RemovePerson", ReplyAction="http://tempuri.org/IPersonAccountService/RemovePersonResponse")]
        System.Threading.Tasks.Task<string> RemovePersonAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddCustomerToAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddCustomerToAccountResponse")]
        string AddCustomerToAccount(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.CustomerDto customerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddCustomerToAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddCustomerToAccountResponse")]
        System.Threading.Tasks.Task<string> AddCustomerToAccountAsync(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.CustomerDto customerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddLawyerToAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddLawyerToAccountResponse")]
        string AddLawyerToAccount(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.LawyerDto lawyerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddLawyerToAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddLawyerToAccountResponse")]
        System.Threading.Tasks.Task<string> AddLawyerToAccountAsync(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.LawyerDto lawyerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddGeneralAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddGeneralAccountResponse")]
        string AddGeneralAccount(Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto generalAccountDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddGeneralAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddGeneralAccountResponse")]
        System.Threading.Tasks.Task<string> AddGeneralAccountAsync(Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto generalAccountDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/RemoveGeneralAccount", ReplyAction="http://tempuri.org/IPersonAccountService/RemoveGeneralAccountResponse")]
        string RemoveGeneralAccount(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/RemoveGeneralAccount", ReplyAction="http://tempuri.org/IPersonAccountService/RemoveGeneralAccountResponse")]
        System.Threading.Tasks.Task<string> RemoveGeneralAccountAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetGeneralAccount", ReplyAction="http://tempuri.org/IPersonAccountService/GetGeneralAccountResponse")]
        Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto GetGeneralAccount(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetGeneralAccount", ReplyAction="http://tempuri.org/IPersonAccountService/GetGeneralAccountResponse")]
        System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto> GetGeneralAccountAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddIndexAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddIndexAccountResponse")]
        string AddIndexAccount(Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto indexAccountDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddIndexAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddIndexAccountResponse")]
        System.Threading.Tasks.Task<string> AddIndexAccountAsync(Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto indexAccountDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/RemoveIndexAccount", ReplyAction="http://tempuri.org/IPersonAccountService/RemoveIndexAccountResponse")]
        string RemoveIndexAccount(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/RemoveIndexAccount", ReplyAction="http://tempuri.org/IPersonAccountService/RemoveIndexAccountResponse")]
        System.Threading.Tasks.Task<string> RemoveIndexAccountAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetIndexAccount", ReplyAction="http://tempuri.org/IPersonAccountService/GetIndexAccountResponse")]
        Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto GetIndexAccount(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/GetIndexAccount", ReplyAction="http://tempuri.org/IPersonAccountService/GetIndexAccountResponse")]
        System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto> GetIndexAccountAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddAccountResponse")]
        string AddAccount(Valiasr.UI.WPF.ServiceReferencePerson.AccountDto accountDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonAccountService/AddAccount", ReplyAction="http://tempuri.org/IPersonAccountService/AddAccountResponse")]
        System.Threading.Tasks.Task<string> AddAccountAsync(Valiasr.UI.WPF.ServiceReferencePerson.AccountDto accountDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonAccountServiceChannel : Valiasr.UI.WPF.ServiceReferencePerson.IPersonAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonAccountServiceClient : System.ServiceModel.ClientBase<Valiasr.UI.WPF.ServiceReferencePerson.IPersonAccountService>, Valiasr.UI.WPF.ServiceReferencePerson.IPersonAccountService {
        
        public PersonAccountServiceClient() {
        }
        
        public PersonAccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonAccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonAccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonAccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Valiasr.UI.WPF.ServiceReferencePerson.PersonDto GetPersonByNationalIdentity(string nationalIdentity) {
            return base.Channel.GetPersonByNationalIdentity(nationalIdentity);
        }
        
        public System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.PersonDto> GetPersonByNationalIdentityAsync(string nationalIdentity) {
            return base.Channel.GetPersonByNationalIdentityAsync(nationalIdentity);
        }
        
        public Valiasr.UI.WPF.ServiceReferencePerson.PersonDto GetPersonById(System.Guid id) {
            return base.Channel.GetPersonById(id);
        }
        
        public System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.PersonDto> GetPersonByIdAsync(System.Guid id) {
            return base.Channel.GetPersonByIdAsync(id);
        }
        
        public string AddPerson(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto) {
            return base.Channel.AddPerson(personDto);
        }
        
        public System.Threading.Tasks.Task<string> AddPersonAsync(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto) {
            return base.Channel.AddPersonAsync(personDto);
        }
        
        public string UpdatePerson(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto) {
            return base.Channel.UpdatePerson(personDto);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePersonAsync(Valiasr.UI.WPF.ServiceReferencePerson.PersonDto personDto) {
            return base.Channel.UpdatePersonAsync(personDto);
        }
        
        public string RemovePerson(System.Guid id) {
            return base.Channel.RemovePerson(id);
        }
        
        public System.Threading.Tasks.Task<string> RemovePersonAsync(System.Guid id) {
            return base.Channel.RemovePersonAsync(id);
        }
        
        public string AddCustomerToAccount(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.CustomerDto customerDto) {
            return base.Channel.AddCustomerToAccount(accountId, customerDto);
        }
        
        public System.Threading.Tasks.Task<string> AddCustomerToAccountAsync(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.CustomerDto customerDto) {
            return base.Channel.AddCustomerToAccountAsync(accountId, customerDto);
        }
        
        public string AddLawyerToAccount(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.LawyerDto lawyerDto) {
            return base.Channel.AddLawyerToAccount(accountId, lawyerDto);
        }
        
        public System.Threading.Tasks.Task<string> AddLawyerToAccountAsync(System.Guid accountId, Valiasr.UI.WPF.ServiceReferencePerson.LawyerDto lawyerDto) {
            return base.Channel.AddLawyerToAccountAsync(accountId, lawyerDto);
        }
        
        public string AddGeneralAccount(Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto generalAccountDto) {
            return base.Channel.AddGeneralAccount(generalAccountDto);
        }
        
        public System.Threading.Tasks.Task<string> AddGeneralAccountAsync(Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto generalAccountDto) {
            return base.Channel.AddGeneralAccountAsync(generalAccountDto);
        }
        
        public string RemoveGeneralAccount(System.Guid id) {
            return base.Channel.RemoveGeneralAccount(id);
        }
        
        public System.Threading.Tasks.Task<string> RemoveGeneralAccountAsync(System.Guid id) {
            return base.Channel.RemoveGeneralAccountAsync(id);
        }
        
        public Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto GetGeneralAccount(int code) {
            return base.Channel.GetGeneralAccount(code);
        }
        
        public System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.GeneralAccountDto> GetGeneralAccountAsync(int code) {
            return base.Channel.GetGeneralAccountAsync(code);
        }
        
        public string AddIndexAccount(Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto indexAccountDto) {
            return base.Channel.AddIndexAccount(indexAccountDto);
        }
        
        public System.Threading.Tasks.Task<string> AddIndexAccountAsync(Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto indexAccountDto) {
            return base.Channel.AddIndexAccountAsync(indexAccountDto);
        }
        
        public string RemoveIndexAccount(System.Guid id) {
            return base.Channel.RemoveIndexAccount(id);
        }
        
        public System.Threading.Tasks.Task<string> RemoveIndexAccountAsync(System.Guid id) {
            return base.Channel.RemoveIndexAccountAsync(id);
        }
        
        public Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto GetIndexAccount(string code) {
            return base.Channel.GetIndexAccount(code);
        }
        
        public System.Threading.Tasks.Task<Valiasr.UI.WPF.ServiceReferencePerson.IndexAccountDto> GetIndexAccountAsync(string code) {
            return base.Channel.GetIndexAccountAsync(code);
        }
        
        public string AddAccount(Valiasr.UI.WPF.ServiceReferencePerson.AccountDto accountDto) {
            return base.Channel.AddAccount(accountDto);
        }
        
        public System.Threading.Tasks.Task<string> AddAccountAsync(Valiasr.UI.WPF.ServiceReferencePerson.AccountDto accountDto) {
            return base.Channel.AddAccountAsync(accountDto);
        }
    }
}
