//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valiasr.UI.WPF.AccountServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://schemas.datacontract.org/2004/07/Valiasr.Service")]
    [System.SerializableAttribute()]
    public partial class CustomerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HagheBardashtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PortionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HagheBardasht {
            get {
                return this.HagheBardashtField;
            }
            set {
                if ((this.HagheBardashtField.Equals(value) != true)) {
                    this.HagheBardashtField = value;
                    this.RaisePropertyChanged("HagheBardasht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Portion {
            get {
                return this.PortionField;
            }
            set {
                if ((this.PortionField.Equals(value) != true)) {
                    this.PortionField = value;
                    this.RaisePropertyChanged("Portion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountServiceReference.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/CanBardasht", ReplyAction="http://tempuri.org/IAccountService/CanBardashtResponse")]
        bool CanBardasht(string accountNo, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/CanBardasht", ReplyAction="http://tempuri.org/IAccountService/CanBardashtResponse")]
        System.Threading.Tasks.Task<bool> CanBardashtAsync(string accountNo, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Bardasht", ReplyAction="http://tempuri.org/IAccountService/BardashtResponse")]
        bool Bardasht(string account, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Bardasht", ReplyAction="http://tempuri.org/IAccountService/BardashtResponse")]
        System.Threading.Tasks.Task<bool> BardashtAsync(string account, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetCustomerByAccountNo", ReplyAction="http://tempuri.org/IAccountService/GetCustomerByAccountNoResponse")]
        Valiasr.UI.WPF.AccountServiceReference.CustomerDto[] GetCustomerByAccountNo(string accountNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetCustomerByAccountNo", ReplyAction="http://tempuri.org/IAccountService/GetCustomerByAccountNoResponse")]
        System.Threading.Tasks.Task<Valiasr.UI.WPF.AccountServiceReference.CustomerDto[]> GetCustomerByAccountNoAsync(string accountNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : Valiasr.UI.WPF.AccountServiceReference.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<Valiasr.UI.WPF.AccountServiceReference.IAccountService>, Valiasr.UI.WPF.AccountServiceReference.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CanBardasht(string accountNo, double amount) {
            return base.Channel.CanBardasht(accountNo, amount);
        }
        
        public System.Threading.Tasks.Task<bool> CanBardashtAsync(string accountNo, double amount) {
            return base.Channel.CanBardashtAsync(accountNo, amount);
        }
        
        public bool Bardasht(string account, double amount) {
            return base.Channel.Bardasht(account, amount);
        }
        
        public System.Threading.Tasks.Task<bool> BardashtAsync(string account, double amount) {
            return base.Channel.BardashtAsync(account, amount);
        }
        
        public Valiasr.UI.WPF.AccountServiceReference.CustomerDto[] GetCustomerByAccountNo(string accountNo) {
            return base.Channel.GetCustomerByAccountNo(accountNo);
        }
        
        public System.Threading.Tasks.Task<Valiasr.UI.WPF.AccountServiceReference.CustomerDto[]> GetCustomerByAccountNoAsync(string accountNo) {
            return base.Channel.GetCustomerByAccountNoAsync(accountNo);
        }
    }
}
